# Generated by Django 5.1 on 2024-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsboardapp', '0003_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='сategory',
            field=models.ManyToManyField(to='newsboardapp.category'),
        ),
    ]
