# Generated by Django 5.1 on 2024-09-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsboardapp', '0004_post_сategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
